# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Desktop',
        ),
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='Laptop',
        ),
        migrations.RenameModel(
            old_name='Desktops',
            new_name='Mobile',
        ),
    ]
